export const SET_INVOICE_REQUEST = 'invoices/SET_INVOICE_REQUEST';
export const CREATE_INVOICE_REQUEST = 'invoices/CREATE_INVOICE_REQUEST';
export const UPDATE_INVOICE_REQUEST = 'invoices/UPDATE_INVOICE_REQUEST';
export const DELETE_INVOICE_REQUEST = 'invoices/DELETE_INVOICE_REQUEST';
export const LOAD_INVOICES_REQUEST = 'invoices/LOAD_INVOICES_REQUEST';
export const SET_INVOICES = 'invoices/SET_INVOICES';
