export const LOAD_CUSTOMERS_REQUEST = 'customers/LOAD_CUSTOMERS_REQUEST';
export const CREATE_CUSTOMER_REQUEST = 'customers/CREATE_CUSTOMER_REQUEST';
export const UPDATE_CUSTOMER_REQUEST = 'customers/UPDATE_CUSTOMER_REQUEST';
export const DELETE_CUSTOMER_REQUEST = 'customers/DELETE_CUSTOMER_REQUEST';

export const CREATE_CUSTOMER_FAILURE = 'CREATE_CUSTOMER_FAILURE';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_FAILURE = 'DELETE_CUSTOMER_FAILURE';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
export const LOAD_CUSTOMERS_FAILURE = 'LOAD_CUSTOMERS_FAILURE';
export const LOAD_CUSTOMERS_SUCCESS = 'LOAD_CUSTOMERS_SUCCESS';
export const UPDATE_CUSTOMER_FAILURE = 'UPDATE_CUSTOMER_FAILURE';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
