export const SET_CUSTOMER_REQUEST = 'customers/SET_CUSTOMER_REQUEST';
export const CREATE_CUSTOMER_REQUEST = 'customers/CREATE_CUSTOMER_REQUEST';
export const UPDATE_CUSTOMER_REQUEST = 'customers/UPDATE_CUSTOMER_REQUEST';
export const DELETE_CUSTOMER_REQUEST = 'customers/DELETE_CUSTOMER_REQUEST';
