export const SET_PRODUCT_REQUEST = 'products/SET_PRODUCT_REQUEST';
export const CREATE_PRODUCT_REQUEST = 'products/CREATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_REQUEST = 'products/UPDATE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_REQUEST = 'products/DELETE_PRODUCT_REQUEST';
export const SET_PRODUCTS = 'products/SET_PRODUCTS';
