export const SET_INVOICE_ITEM_REQUEST = 'invoice_items/SET_INVOICE_ITEM_REQUEST';
export const CREATE_INVOICE_ITEM_REQUEST = 'invoice_items/CREATE_INVOICE_ITEM_REQUEST';
export const UPDATE_INVOICE_ITEM_REQUEST = 'invoice_items/UPDATE_INVOICE_ITEM_REQUEST';
export const DELETE_INVOICE_ITEM_REQUEST = 'invoice_items/DELETE_INVOICE_ITEM_REQUEST';
export const SET_INVOICE_ITEMS = 'invoice_items/SET_INVOICE_ITEMS';
