export const SET_PRODUCT_REQUEST = 'customers/LOAD_PRODUCTS_REQUEST';
export const CREATE_PRODUCT_REQUEST = 'customers/CREATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_REQUEST = 'customers/UPDATE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_REQUEST = 'customers/DELETE_PRODUCT_REQUEST';
